ansible_connection: amazon.aws.aws_ssm
ansible_aws_ssm_region: us-east-1
ansible_aws_ssm_bucket_name: ansible-ssm-demo-ssm-transfer-f8c0dec2

# Ubuntu AMI uses the "ubuntu" user (even though SSM isn't SSH)
ansible_user: ubuntu

# Optional: makes commands run with sudo
ansible_become: true
