plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

# Only target instances for THIS project
filters:
  tag:Project: ansible-ssm-bootstrap
  instance-state-name: running

# Using instance_id as the hostname Ansible sees
hostnames:
  - instance-id

# Group hosts by tag (will neeed later)
keyed_groups:
  - key: tags.Environment
    prefix: env_
  - key: tags.Name
    prefix: name_
